# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7da973edc4d6b5fdcf31d5842f2c321c67103e5b5e21ca6b004b439b566e9fb303291e3c47b3d1f1abef977a255d3971b294cba2d26a60b5295132c21bff6f3e

test:
  secret_key_base: 4b5ec29786abe9d3d0b11581468d77f1ea3a56a8a028768102f5ebe8404e2e975cad565459948f3160c73128c5b6e0c68a93f77f55559aa2effea4c3eb34d920

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
